{"name": "test_moving_item_to_archive_exist_there", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'to_graphql'", "trace": "self = <test.api_and_ui_tests.test_archive_item.TestArchiveItem testMethod=test_moving_item_to_archive_exist_there>\n\n    def setUp(self) -> None:\n        \"\"\"\n        Sets up the test environment by initializing APIWrapper and loading configuration.\n        \"\"\"\n        self.api_request = APIWrapper()\n        self.config = ConfigProvider.load_config_json()\n    \n        self.browser = BrowserWrapper()\n        self.config = ConfigProvider.load_config_json()\n        self.driver = self.browser.get_driver(self.config[\"login_url\"])\n    \n        login_page = LoginPage(self.driver)\n        login_page.login_flow(self.config[\"email\"], self.config[\"password\"])\n    \n        default_task_payload = DefaultItemPayload()\n        self.task_name = default_task_payload.name\n    \n        new_task = CreateItem(self.api_request)\n>       self.task_body = new_task.post_create_item(default_task_payload.to_graphql())\n\ntest_archive_item.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <logic.logic_api.create_item.CreateItem object at 0x000001BACA16D290>\ntask_payload = {'query': 'mutation { create_item (board_id: 1583771705, group_id: \"new_group29179\", item_name: \"SQMUSOVMXLDJ\", column_values: \"{\\\\\"pos\\\\\": 195168, \\\\\"with_undo_data\\\\\": true}\") { id } }'}\n\n    def post_create_item(self, task_payload):\n        \"\"\"\n        Sends a POST request to create a new task with the provided payload.\n    \n        :param task_payload: The payload containing task details to be created.\n        :return: The response from the POST request.\n        \"\"\"\n        url = f\"{self.config['api_url']}\"\n>       return self._request.post_request(url, self.config[\"header\"], task_payload.to_graphql())\nE       AttributeError: 'dict' object has no attribute 'to_graphql'\n\n..\\..\\logic\\logic_api\\create_item.py:28: AttributeError"}, "description": "\n        Tests the functionality of archiving an item and verifies\n         that the item is present in the archive.\n        ", "start": 1723397658213, "stop": 1723397667009, "uuid": "5fa88006-f950-4e87-8b3b-a463f64891da", "historyId": "29f99ae1852644ad135fd3110604bab6", "testCaseId": "29f99ae1852644ad135fd3110604bab6", "fullName": "test_archive_item.TestArchiveItem#test_moving_item_to_archive_exist_there", "labels": [{"name": "suite", "value": "test_archive_item"}, {"name": "subSuite", "value": "TestArchiveItem"}, {"name": "host", "value": "DESKTOP-IGNAR84"}, {"name": "thread", "value": "6348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_archive_item"}]}